spring.application.name=Pratica_SpringBoot

# Configuração do servidor
server.port=8080

# Configurações do banco de dados
spring.datasource.url=jdbc:mysql://localhost:3306/pratica_springboot?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configurações do JPA/Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Configurações de logging
logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG

# pasta de logs
logging.file.path=logs

# arquivo principal
logging.file.name=logs/app.log

# armazenamento de imagens de usuário
app.usuario.imagens-base-dir=imagens-usuarios

# upload de imagens
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=6MB